server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka #standalone
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #cluster

  instance:
    instance-id: order80
    prefer-ip-address: true # 使用 IP 地址進行註冊