spring:
  profiles:
    active: local1
  application:
    name: cloud-payment-service

server:
  port: 8001

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka # standalone
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #cluster

    # registry-fetch-interval-seconds: 5 # 從 Eureka 服務器獲取註冊表信息的頻率


  instance:
    instance-id: payment8001
    prefer-ip-address: true # 使用 IP 地址進行註冊
    # lease-renewal-interval-in-seconds: 1 # 發送心跳的時間間隔(默認30秒)
    # lease-expiration-duration-in-seconds: 2 # eureka服務端在收到最後一次心跳後等待時間上限 (默認90秒 超時將剔除)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities