server:
  port: 7001

eureka:
  instance:
    # hostname: localhost #實例名稱 for standalone
    hostname: eureka7001.com #實例名稱 for cluster
  client:
    register-with-eureka: false #不註冊自己
    fetch-registry: false #不需要檢索服務
    service-url:
      # 設置與 eureka server 交互的地址查詢服務和註冊服務都需要依賴這個地址
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka # standalone
      defaultZone: http://eureka7002.com:7002/eureka # cluster

  server:
    enable-self-preservation: false # 自我保護模式關閉 就代表服務一斷線就會被剔除服務清單
    #eviction-interval-timer-in-ms: 1000 # 驅逐間隔時間設置改為1秒
    eviction-interval-timer-in-ms: 60000 # 驅逐間隔時間設置為1分鐘
    renewal-percent-threshold: 0.45